### PR TITLE
Event Bus

### PR DESCRIPTION
**Pull request by s0cks**
### Description of the Change

This  pull request is to reduce & clean up the event listener code to make it more decoupled & flexible by leveraging Guava's EventBus.

 **Ideally this will be the first part of a 2 part series of PRs to refactor this system.** 

This part handles the initial work to refactor and clean it up. 

The second part will add:
 
 -  listeners can independently annotate which "Side" - or thread, it should be executed on. Improving throughput and performance.
 -  ???

### Testing

Minor regression testing against the UI to check things like console closing / opening & localization changes being applied correctly, and ensure that event handlers are properly being executed on the Swing Thread. 

More is always welcome.

### Related Issues

N/A; Figured this was a good first step in allowing the launcher to multi-task

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
Ironically, we both came to similar wishes at the same time. Consider looking at my #606 series?

**Comment by s0cks** [comment]
@Doomsdayrs I'm currently refactoring the event code, and adding some new tricks. I am also working on making the launcher more parallel as a result of that.

Perhaps we should touch base and identify strategies so we don't step on each other's toes?

**Comment by s0cks** [comment]
Please message me on discord @ xswizzzlex

**Comment by s0cks** [comment]
You guys got this
~ Tazz

**Pull request closed without merging**
