### PR TITLE
Fetch stylesheets from the correct module (Java 9+)

### PR DESCRIPTION
**Pull request by jamierocks**
Fixes GH-395.

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
The same issue exists for loading fonts: https://github.com/ATLauncher/ATLauncher/blob/master/src/main/java/com/atlauncher/utils/Resources.java#L92

Also can you add in a line to the `CHANGELOG.md`

```
- Some description here [#395]
```

**Comment by RyanTheAllmighty** [comment]
Thankyou. That body font looks super dodgy on OSX :\

**Comment by jamierocks** [comment]
> OSX

It does, as I mentioned a few weeks back - though that's actually a screenshot of Plasma (admittedly Flat Remix does look similar) :p

**Comment by RyanTheAllmighty** [comment]
Very odd. On Windows it looks fine, and the tab font looks smooth and nice as well, so it's just the body font. Maybe it's scaling the font odd due to font size or something, not sure

**Pull request merged**
