### PR TITLE
Add xrandr to requirements for RPM

### LINKED ISSUE #690: xrandr must be installed to launch Minecraft
I'm using ATLauncher on Fedora 37, and was receiving the following error when launching a Minecraft 1.12.2 pack:

```
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:951)
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
[10:56:10] [main/INFO]: [java.lang.Throwable:printEnclosedStackTrace:709]: 	... 27 more
```

This issue was caused by the `xrandr` command being unavailable to Java. Installing the `xrandr` package fixed the problem.

Adding that package as a requirement to the specfile should make it easier for others to use ATLauncher in the future

### PR DESCRIPTION
**Pull request by Doomsdayrs**
### Description of the Change

Add `xrandr` as a requirement for RPM based distributions. This fixes issues with old versions of minecraft and their missing dependencies.

### Testing

- [ ] Create RPM package
- [ ] Install RPM package

### Related Issues

Closes #690

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
Good to go @Doomsdayrs ? Still in draft ATM

**Comment by Doomsdayrs** [comment]
How do I create the rpm file, I want to test it that way first

**Comment by RyanTheAllmighty** [comment]
There's a `build.bat` and `build.sh` in [packaging/linux](https://github.com/ATLauncher/ATLauncher/tree/master/packaging/linux) directory.

The shell script one may not work, I've not tested. But if not, just follow what's done in the [Dockerfile](https://github.com/ATLauncher/ATLauncher/blob/master/packaging/linux/deb/Dockerfile)

**Comment by Doomsdayrs** [comment]
As far as I am concerned then, it should not be a problem

**Pull request merged**
