### PR TITLE
Remove Old Logging & Use Log4J2

### PR DESCRIPTION
**Pull request by s0cks**
### Description of the Change

This change is to remove the old logging and leverage log4j2

### Testing

Extensive regression testing locally, though more is always welcome.

Existing Functionality should ideally be preserved 

### Related Issues

N/A; Figured it was a good enhancement

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
The main issue I have with this is that by not going through the LogManager existing it won't print out details for stack traces as well as not doing remote error reporting which is super helpful.

Also looks like there's no modularity on debug level reporting, so higher debug level on launch prints more, which is another thing that is super helpful to have.

Why does the LogManager instance for log4j2 need to be called in every class? Does this provide any benefit over having a centralised LogManager with all those convenience methods?

**Comment by s0cks** [comment]
> The main issue I have with this is that by not going through the LogManager existing it won't print out details for stack traces as well as not doing remote error reporting which is super helpful.

So detailed stack traces like the following?:
```text
22:48:04.775 [main] ERROR - This is an error
java.lang.RuntimeException: Failed
	at com.atlauncher.App.main(App.java:269) [main/:?]
```

these can be generated like such:
```java
LOG.error("This is an {}", "error", new RuntimeException("Failed"));
```

As far as reporting for the exceptions, please take a look at ```log4j2.xml``` & ```LauncherReportingAppender```:
```xml
    <Appenders>
        <LauncherConsole name="LogToLauncherConsole"/>

        <LauncherReporter name="LogToReporter">
            <Filters>
                <!-- filter based on ERROR level -->
                <ThresholdFilter level="ERROR" onMatch="ACCEPT" onMismatch="DENY"/>
                <!-- filter based on errors to not be reported -->
                <MarkerFilter marker="NoReporting" onMatch="DENY" onMismatch="ACCEPT"/>
            </Filters>
        </LauncherReporter>

       .........
    </Appenders>

     <Loggers>
        <Logger name="Minecraft" level="INFO">
            <AppenderRef ref="LogToLauncherConsole"/>
        </Logger>

        <Logger name="com.atlauncher" level="INFO">
            <AppenderRef ref="LogToRollingFile"/>
            <Appenderref ref="LogToLauncherConsole"/>
            <AppenderRef ref="LogToReporter"/>
        </Logger>

        ......
     </Loggers>
```

I added an appender for the reporter so it will report exceptions. You can use a marker to filter them out like so:

```java
public static void disable() {
    if (client != null) {
        try {
            Sentry.close();
            client = null;
        } catch (Exception e) {
            // will skip the LauncherReportingAppender and only print to the console & file.
            LOG.error(MarkerManager.getMarker("NoReporting"), "Error disabling error reporting", e);
        }
    }
}
```

> Also looks like there's no modularity on debug level reporting, so higher debug level on launch prints more, which is another thing that is super helpful to have.

This is true but I also really advise against adding extra "levels" to log messages. This can lead to extra complexity for no value. DEBUG is the level you should use for that as you can disable those by setting the logger level higher. 
 
> Why does the LogManager instance for log4j2 need to be called in every class? Does this provide any benefit over having a centralised LogManager with all those convenience methods?

In clean code and good design you always want to use a scoped logger. This pattern allows you to compose loggers that can be customized and provide extra metadata. For instance, the classical example is a logger for an http request scope, this allows you to add request context cleanly to the logger so when log events are called it will inject that metadata into the logs for better debugging/tracing

By calling ```LogManager.getLogger()``` you construct a new logger instance for your scope.

Generally you want to have a Logger for each class, sometimes even per function depending on the need. While still technically doable to make a single logger instance you are limiting yourself - as well as also imposing thread safety concerns with shared access.

**Comment by RyanTheAllmighty** [comment]
@s0cks sorry for the delay. But happy to go ahead with this. There's a few conflicts and likely quite a few areas that I've added that are missing now, but happy to proceed if you're happy to fix it all up, then I can review. Just let me know either way :)

**Comment by s0cks** [comment]
I'll take a look at fixing it up later today
~ Tazz

**Comment by RyanTheAllmighty** [comment]
Test

**Comment by s0cks** [comment]
@RyanTheAllmighty please review and merge soon before I have to do another rebase 😭 
~ Tazz

**Pull request merged**
