### PR TITLE
Fixes title being cut off

### PR DESCRIPTION
**Pull request by MiroslavTsvetomirovPavlov**
### Description of the Change

Changes the CollapsiblePanel class so the title doesn't get cut off as in issue #867

### Testing

Tested

### Related Issues

https://github.com/ATLauncher/ATLauncher/issues/867

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
Tried this out and titles still seem to be cut off for me:

image

**Comment by MiroslavTsvetomirovPavlov** [comment]
I pushed another commit to work with every title format. The previous one worked only when the format was "Instance Name".
This should do it.

**Comment by RyanTheAllmighty** [comment]
Still seeing it cut off:

image

I don't think just adding extra spacing to the width of the title is the right solution, I think it needs to be dynamic similar to the way `IconTitledBorder` works

**Comment by RyanTheAllmighty** [comment]
Going to close this one off as it seems there's no solution currently developed which works accurately

**Pull request closed without merging**
