### PR TITLE
Speed up CreatePackTab

### PR DESCRIPTION
**Pull request by Doomsdayrs**
### Description of the Change

Resolves issues as described by #931 

### Testing

- [x] Typing very very fast (lots of types and backspaces)
- [x] Step 1 but with `command + a` added on at the end
- [x] Make a very long line until text wraps.

### Related Issues

#931

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
Does this fix the wrapping issue as well? Description box doesn't wrap, not sure if it was mentioned in the issue or not

**Comment by kam106** [comment]
Description text wrapping should be mentioned on the issue, I can go back and made it clearer if it's not added.

**Comment by Doomsdayrs** [comment]
> Does this fix the wrapping issue as well? Description box doesn't wrap, not sure if it was mentioned in the issue or not

[45a9190](https://github.com/ATLauncher/ATLauncher/pull/933/commits/45a9190728d7eb7fc3fe869f411eaa220e6a09a0)?

**Review by RyanTheAllmighty — APPROVED** [review]
@Doomsdayrs same with this one, might want to rebase into master instead so the fix can be pushed out

**Comment by Doomsdayrs** [comment]
> @Doomsdayrs same with this one, might want to rebase into master instead so the fix can be pushed out

Oki doki

**Pull request merged**
