### PR TITLE
Add xdg-portal FileChooser via extension jar

### PR DESCRIPTION
**Pull request by Doomsdayrs**
### Description of the Change

If having a dbus API messes with Minecraft Forge 1.16.#,
 We can simply have another application handle the calls,
 simplifying what we need to do.
 
Utilizing the newly created program hosted [here](https://gitlab.com/Doomsdayrs/atlauncherx-flatpak)

### Testing

- I have tested adding a jar, it seems to add the jar but the console throws out strange errors regarding zip? 
Could you take a look at them?
- I have tested Minecraft 1.16 and 1.16.5

### Related Issues

#564

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
I'd definitely want to avoid having a separate jar not sourced and built in our GitHub org included and randomly run for flatpak users, it sounds very sketch.

Ideally I want to solve the issue through the source itself by fixing the classpath issue.

Will keep this as a backup and go this route if I can't find any solution to that issue, but yeah I'd definitely want to insist the source is moved into this repo or organisation and also built in this repo/org and hosted on our CDN to keep things transparent and clear that it's legit.

If I can't find any solution to the original issue by, let's say next weekend, then we'll continue with this.

**Comment by RyanTheAllmighty** [comment]
Alright I found a solution in #564, it's as I thought, some of our deps were poisining the processes that runs the Forge processes, so just running with a clean/system classloader fixes it

**Comment by Doomsdayrs** [comment]
While the proper solution does in fact solve the dbus issue, you did express concern in regards to the increase of file size.

To solve this, I'd suggest using the exclusions I have to lower file size.

https://gitlab.com/Doomsdayrs/atlauncherx-flatpak/-/blob/main/build.gradle.kts#L39

**Comment by Doomsdayrs** [comment]
and thus, closed as proper solution found

**Pull request closed without merging**
