### PR TITLE
Added custom launcher names

### PR DESCRIPTION
**Pull request by modmuss50**
This adds LAUNCHER_NAME into the Constants file to make it easier to rename the launcher.

I don't know why git has made 3 commits. If you would like me to compress it down into one I don't mind doing that. Sorry.

### CODE REVIEW

**Comment by lexware** [comment]
I can make a version which gets the data for Maven if you like.

**Comment by modmuss50** [comment]
@lexware I would not mind that, just check with @RyanTheAllmighty first I guess.

**Comment by RyanTheAllmighty** [comment]
It's probably just easier to use it from the Constants file rather than Maven is it not @lexware

**Comment by lexware** [comment]
I find less edits is usually easier :)

—

**Comment by lexware** [comment]
@RyanTheAllmighty you could even load the LauncherVersion

—

**Comment by RyanTheAllmighty** [comment]
I don't know, I mean I know I use the Constants file myself when builds are created on the Jenkins build server to auto increment it, but again that's not viable for alot of people.

I personally feel as though it's extra code and processing power required to read in the pom and parse it for those values rather than just reading from the Constants file. Again I may be alone in that feeling, so I have no idea, lol

**Comment by lexware** [comment]
Here is an example: https://gist.github.com/lexware/e25ab4638e279147630a

**Comment by RyanTheAllmighty** [comment]
I'm going to accept this and use the Constants method at least for now. I personally see more benefit to this method

**Pull request merged**
