### PR TITLE
WIP: Cleanup build.gradle

### PR DESCRIPTION
**Pull request by s0cks**
### Description of the Change

This PR is to cleanup the build.gradle file a little bit and move the dependency versions to the gradle.properties file, this should help make version updates easier operationally.

### Testing

Refresh gradle project and verify versions

### Related Issues

N/A; Good Housekeeping

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
This just adds verbosity to the gradle script.

I don't see any plausible benefit

**Comment by s0cks** [comment]
Well it's easier to automate operational  things like version updates to dependencies

**Comment by s0cks** [comment]
Oh and the versions list can be copied to the jar and displayed to the user in your about tab during package time

**Comment by Doomsdayrs** [comment]
> Well it's easier to automate operational things like version updates to dependencies

1. There are most certainly CI bots that can handle gradle updates.
2. Automatic dependency upgrades are a nightmare logistically. As you should be reviewing the update change log to ensure the program doesn't suddenly stop working

> Oh and the versions list can be copied to the jar and displayed to the user in your about tab during package time

This can be done via gradle task.

**Comment by s0cks** [comment]
KISS

**Comment by Doomsdayrs** [comment]
> KISS

????

**Comment by s0cks** [comment]
https://dzone.com/articles/software-design-principles-dry-and-kiss

**Comment by Doomsdayrs** [comment]
> https://dzone.com/articles/software-design-principles-dry-and-kiss

Stating acronyms does not validate your point. You are doing the opposite of keeping it simple. You are unnecessarily complicating an already existing system for supposed benefits that are already present in said system.

**Pull request closed without merging**
