### PR TITLE
Misc fixes for random issues

### PR DESCRIPTION
**Pull request by dgelessus**
Fixes some random issues that I came across. Nothing really interesting to see, but there should be fewer bugs than before. `:)`

### CODE REVIEW

**Comment by RyanTheAllmighty** [comment]
Can any of these fixes be backported to the 3.2.3.2 branch? If so that would be great as I don't see 3.3.0.0 ever being released unfortunately

**Comment by dgelessus** [comment]
Some of these were 3.3.0.0 only, such as the config issue. Not sure about the others. As I mentioned in the other issue, I don't have access to my PC at the moment, so I won't be able to do anything for a few weeks.

**Comment by dgelessus** [comment]
Yeah, it looks like there is really nothing to backport.

* e755119 fixes a bug from when `getOSStorageDir` was moved from `Utils` to `OS`, in master everything is correct.
* 25b2fff is just a code quality change, not really worth backporting.
* 940876c fixes a bug from when the config format was changed to JSON, so it's also not present in master.
* 980afee fixes a concurrency bug in `DownloadPool`, which is new in the 3.3.0.0 branch, so this doesn't affect master either.

**Comment by RyanTheAllmighty** [comment]
NO problems at all then, cheers again :)

**Pull request merged**
