### PR TITLE
#279: added a string versionLength to hold the max width of the versi…

### PR DESCRIPTION
**Pull request by flaw600**
…ons list and set the width of the versionDropdown to that value + 20 (for readability)

### CODE REVIEW

**Comment by flaw600** [comment]
@RyanTheAllmighty as you requested. Thanks for testing!

**Comment by RyanTheAllmighty** [comment]
Couple of issues, did you want to fix it or should I merge this in and then fix them after?

I made this change so that it accounts for the actual rendered text width while also keeping a minimum size and maximum:

```


        for (PackVersion version : versions) {
            versionLength = Math.max(versionLength, getFontMetrics(Utils.getFont()).stringWidth(version.toString()) + 25);
        }

        // ensure the dropdown is at least 200px wide
        versionLength = Math.max(versionLength, 200);

        // ensure the dropdown is at most 250px wide to prevent overflow
        versionLength = Math.min(versionLength, 250);

        versionsDropDown.setPreferredSize(new Dimension(versionLength, 25));
```

**Comment by flaw600** [comment]
@RyanTheAllmighty I see what you did and agree with most of it, but I'd like to point out that having a limit to the size is what causes the issue in the first place. If you're going to set a maximum, you should probably post a developer/pack guideline stating a max character limit for version names. Just my opinion though. At any rate, my implementation with your edits should be up now

**Comment by RyanTheAllmighty** [comment]
I do agree, but without a max limit it causes the dialog to just stuff up if it's too large. I think this solution is better that what it was, but still not ideal. For now this will do and I'll play around with it and see what else can be done, else it's still an improvement, even if only slightly :P

**Pull request merged**
