### PR TITLE
Improve pom.xml

### PR DESCRIPTION
**Pull request by lexware**
This makes it changing the name of the launcher a shorter process.

### CODE REVIEW

**Comment by modmuss50** [comment]
On this this topic. In my fork of the ATLauncher I added a launcher name string into the constants file. This could also be done on the main repo to aid with changing the name of the launcher.

**Comment by lexware** [comment]
Yes, maybe a properties file with both name and version that maven would write too would be a good idea?

—

**Comment by modmuss50** [comment]
I have never used maven so I could not help with that. But that sounds like a good idea, then it would be very easy to make a custom version of the launcher

**Comment by lexware** [comment]
Yes it would simply be a file like:
<code>
name=${project.name}
version=${project.version}
</code>

**Comment by modmuss50** [comment]
Would that then change the gui names like I was thinking of?

**Comment by lexware** [comment]
Yes you would have to create something to read the names from the file however.

—

**Comment by RyanTheAllmighty** [comment]
Sounds good. @modmuss50 if you wish to make that PR for the launchers name in the constants file I'll be happy to accept it. Something like this in the Constants file:

    public static final String LAUNCHER_NAME = "ATLauncher";

Would be okay with me

**Comment by modmuss50** [comment]
Ok cool, I will do that soon.

**Comment by lexware** [comment]
@modmuss50 if you make a properties file in src/main/resources with name=${project.name} and version=${project.version}, you could use that and add in a getName and getVersion methods in Utils.
Of course this will require some sort of reader to gain the information.

**Comment by s0cks** [comment]
Just use java's properties class to parse the properties file

**Comment by RyanTheAllmighty** [comment]
I don't know, it feels like that would create extra unnecessary code to parse the pom file just to get that when that's what the Constants is for. Maybe I'm alone on that feeling?

**Comment by lexware** [comment]
Reading is as simple as
<code>
String name;
InputStream propsStream = ClassLoader.getSystemResourceAsStream("version.properties");
Properties props = new Properties();
try {
    props.load(propsStream);

    name = props.getProperty("name", "ATLauncher");
} catch(IOException ex) {
    ex.printStackTrace();
} finally {
    try {
        propsStream.close();
    }  catch(IOException ignore) {}
}
</code>

**Pull request merged**
