### PR TITLE
Put Instance on a Diet

### PR DESCRIPTION
**Pull request by Doomsdayrs**
### Description of the Change

The Instance data class is grossly misused, never minding the horrific memory impacts due to storing every single mods data in memory.

We have business code in it, UI code in it, code that isn't even used anymore.

### Testing

- [x] ATLauncher Opens
- [x] Adding Mod Works
- [x] Saving instance changes work
- [x] Reinstall dialog works
- At this point I stopped, Most of my code is not logic changing, simply reformatting and code moving.

### Review

~~Please look at the commits one by one, to ensure that the changes check out, and merge without squashing.~~

### Related Issues

#623 
#606

### CODE REVIEW

**Comment by Doomsdayrs** [comment]
@RyanTheAllmighty With this commit I note some unused functions
https://github.com/ATLauncher/ATLauncher/pull/851/commits/bad84e8d742d8918b5cae9e2fa5a0fd97c080eea

What shall happen to them? Removal?

**Comment by RyanTheAllmighty** [comment]
> @RyanTheAllmighty With this commit I note some unused functions [bad84e8](https://github.com/ATLauncher/ATLauncher/commit/bad84e8d742d8918b5cae9e2fa5a0fd97c080eea)
> 
> What shall happen to them? Removal?

Yeah get rid of them @Doomsdayrs they're unused

**Comment by RyanTheAllmighty** [comment]
Merge without squashing? You sure?

I'll have to take a good look at this one as it makes me nervous to change something so crucial to the function of the app, I'll try to take a look next week

**Comment by Doomsdayrs** [comment]
> Merge without squashing? You sure?

My main worry was commit history getting icky with such a big commit.

> I'll have to take a good look at this one as it makes me nervous to change something so crucial to the function of the app, I'll try to take a look next week

There are no logic changes, just separation of duties into various classes. My main concern is that I did not mess up the logic of anything.

**Comment by Doomsdayrs** [comment]
> I'll have to take a good look at this one as it makes me nervous to change something so crucial to the function of the app, I'll try to take a look next week

Once you do, squash~

**Pull request closed without merging**
