### PR TITLE
Initial switch to Gradle

### PR DESCRIPTION
**Pull request by jamierocks**
To build: gradle build

If you'd like I'll do this for the 3.3.0.0 branch too ;)

### CODE REVIEW

**Comment by jamierocks** [comment]
Okay so currently this is very rudimental.

Currently it's missing out the exe.
Other than that it shadows (shades) all the dependencies into the jar. I know that isn't the intended behaviour, so I'd like to know which ones need to be present and which ones not to be.

I noticed that although the OSX bundle works, it packages it slightly differently - like I said it still works. If you like to know more about configuring the plugin see it's extension documentation : https://github.com/crotwell/gradle-macappbundle/blob/master/src/main/groovy/edu/sc/seis/macAppBundle/MacAppBundlePluginExtension.groovy

**Comment by RyanTheAllmighty** [comment]
Could you fix up the .gitignore back to the format it was, it was much cleaner and easier to ignore all and exclude the files we need

**Comment by jamierocks** [comment]
Alright ;)

**Comment by RyanTheAllmighty** [comment]
Sorry I should've mentioned this before, but any possibility you can target the 3.3.0.0 branch only on this one.

I want to keep any releases before 3.3.0.0 as Maven to keep things rolling if there are bug fixes needed quickly.

**Comment by jamierocks** [comment]
Yeah alright ;)

**Comment by jamierocks** [comment]
I'll finish this up tonight ;)

**Comment by jamierocks** [comment]
Replaced by https://github.com/ATLauncher/ATLauncher/pull/300

**Pull request closed without merging**
