### PR TITLE
Improve OS X bundling with Maven.

### PR DESCRIPTION
**Pull request by jamierocks**
This now simplifies the OS X building, refer to http://mojo.codehaus.org/osxappbundle-maven-plugin/ if you would like to elaborate on this, you can also set the JVM version etc.

### CODE REVIEW

**Comment by lexware** [comment]
Unfortunately I'm not sure if this will work on anything else except OS X because of http://mojo.codehaus.org/osxappbundle-maven-plugin/bundle-mojo.html#javaApplicationStub of course that could be easily fixed if that is the case, so if anyone could test, that would be great.

**Comment by lexware** [comment]
Has anyone been able to test? I now do all of my development on OS X now.

**Comment by RyanTheAllmighty** [comment]
I have no Mac to test unfortunately. I can get my virtualbox osx setup though, can you provide a download link to a newly bundles osx app zip so I can test it out since getting a virtualbox osx setup for building will probably be a pain

**Comment by lexware** [comment]
Sure no problem, will have to do later on however.

—

**Comment by lexware** [comment]
I am building on a mac but I have been able to successfully test it :)

**Comment by lexware** [comment]
After having to strangely move <mainClass>${mainclass}</mainClass>.

**Comment by RyanTheAllmighty** [comment]
I don't think this will merge correctly with the previous PR removing the ApplicationStub and I'm still unsure if these changes to my pom will affect any systems we currently use so I'd rather not touch it at this time

**Comment by jamierocks** [comment]
I did update the pr for the pr changing the permissions, so it could merge correctly, it shouldn't of broken any current system you have. Did you ever get around to testing it?

**Pull request closed without merging**
